apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque # for TLS there is a specific type of secret
data:
  mongo-root-username: dXNlcm5hbWU= # echo -n 'username' | base64
  mongo-root-password: cGFzc3dvcmQ= # echo -n 'password' | base64
