apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.6-bionic
          # resources:
          #   limits:
          #     memory: "512Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: example-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service # a random name
spec:
  selector: # to connect to Pod through label
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017 # this is the port where the service will be exposed for use
      targetPort: 27017 # this has to match the containerPort of the Deployment above
