apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  labels:
    app: mongo-headless
spec:
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  clusterIP: None
