export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
export const GET_RMQ_MESSAGES = "GET_RMQ_MESSAGES";
export const CLEAR_RMQ_MESSAGES = "CLEAR_RMQ_MESSAGES";
export const CREATE_RMQ_SERVER = "CREATE_RMQ_SERVER";
export const DELETE_RMQ_SERVER = "DELETE_RMQ_SERVER";
export const CREATE_CONSUMER = "CREATE_CONSUMER";
export const DELETE_CONSUMER = "DELETE_CONSUMER";
export const DELETE_ALL_CONSUMERS = "DELETE_ALL_CONSUMERS";
export const CREATE_PRODUCER = "CREATE_PRODUCER";
export const START_OVERVIEW_STREAM = "START_OVERVIEW_STREAM";
export const GET_STREAM_DATA = "GET_STREAM_DATA";
export const GET_CONSUMER_ACCEPTED_MESSAGES = "GET_CONSUMER_ACCEPTED_MESSAGES";
export const DELETE_CONSUMER_ACCEPTED_MESSAGES =
  "DELETE_CONSUMER_ACCEPTED_MESSAGES";
